// BASEURL
export const BASEURL = process.env.REACT_APP_BASE_URL;

// LOGIN
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// SIGNUP
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// GET_USERS
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

// GET_USER_PROFILE
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

// UPDATE_USER_PROFILE
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE";

// UPDATE_COVER_PICTURE
export const UPDATE_COVER_PICTURE = "UPDATE_COVER_PICTURE";
export const UPDATE_COVER_PICTURE_SUCCESS = "UPDATE_COVER_PICTURE_SUCCESS";
export const UPDATE_COVER_PICTURE_FAILURE = "UPDATE_COVER_PICTURE_FAILURE";

// GET_FRIENDS
export const GET_FRIENDS = "GET_FRIENDS";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_FAILURE = "GET_FRIENDS_FAILURE";

// GET_FRIENDS_REQUEST
export const GET_FRIENDS_REQUEST = "GET_FRIENDS_REQUEST";
export const GET_FRIENDS_REQUEST_SUCCESS = "GET_FRIENDS_REQUEST_SUCCESS";
export const GET_FRIENDS_REQUEST_FAILURE = "GET_FRIENDS_REQUEST_FAILURE";

// SEND_FRIENDS_REQUEST
export const SEND_FRIENDS_REQUEST = "SEND_FRIENDS_REQUEST";
export const SEND_FRIENDS_REQUEST_SUCCESS = "SEND_FRIENDS_REQUEST_SUCCESS";
export const SEND_FRIENDS_REQUEST_FAILURE = "SEND_FRIENDS_REQUEST_FAILURE";

// CANCEL_FRIENDS_REQUEST
export const CANCEL_FRIENDS_REQUEST = "CANCEL_FRIENDS_REQUEST";
export const CANCEL_FRIENDS_REQUEST_SUCCESS = "CANCEL_FRIENDS_REQUEST_SUCCESS";
export const CANCEL_FRIENDS_REQUEST_FAILURE = "CANCEL_FRIENDS_REQUEST_FAILURE";

// ACCEPT_FRIENDS_REQUEST
export const ACCEPT_FRIENDS_REQUEST = "ACCEPT_FRIENDS_REQUEST";
export const ACCEPT_FRIENDS_REQUEST_SUCCESS = "ACCEPT_FRIENDS_REQUEST_SUCCESS";
export const ACCEPT_FRIENDS_REQUEST_FAILURE = "ACCEPT_FRIENDS_REQUEST_FAILURE";

// REJECT_FRIENDS_REQUEST
export const REJECT_FRIENDS_REQUEST = "REJECT_FRIENDS_REQUEST";
export const REJECT_FRIENDS_REQUEST_SUCCESS = "REJECT_FRIENDS_REQUEST_SUCCESS";
export const REJECT_FRIENDS_REQUEST_FAILURE = "REJECT_FRIENDS_REQUEST_FAILURE";

// GET_FEEDS
export const GET_FEEDS = "GET_FEEDS";
export const GET_FEEDS_SUCCESS = "GET_FEEDS_SUCCESS";
export const GET_FEEDS_FAILURE = "GET_FEEDS_FAILURE";

// GET_OWN_FEEDS
export const GET_OWN_FEEDS = "GET_OWN_FEEDS";
export const GET_OWN_FEEDS_SUCCESS = "GET_OWN_FEEDS_SUCCESS";
export const GET_OWN_FEEDS_FAILURE = "GET_OWN_FEEDS_FAILURE";

// ADD_FEEDS
export const ADD_FEEDS = "ADD_FEEDS";
export const ADD_FEEDS_SUCCESS = "ADD_FEEDS_SUCCESS";
export const ADD_FEEDS_FAILURE = "ADD_FEEDS_FAILURE";

// LIKE_FEED
export const LIKE_FEED = "LIKE_FEED";
export const LIKE_FEED_SUCCESS = "LIKE_FEED_SUCCESS";
export const LIKE_FEED_FAILURE = "LIKE_FEED_FAILURE";


// MESSAGE_SEND
export const MESSAGE_SEND = "MESSAGE_SEND";
export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS";
export const MESSAGE_SEND_FAILURE = "MESSAGE_SEND_FAILURE";

// GET_MESSAGE
export const GET_MESSAGE = "GET_MESSAGE";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_FAILURE = "GET_MESSAGE_FAILURE";


// CHAT_SEND
export const CHAT_SEND = "CHAT_SEND";
export const CHAT_SEND_SUCCESS = "CHAT_SEND_SUCCESS";
export const CHAT_SEND_FAILURE = "CHAT_SEND_FAILURE";

// GET_CHAT
export const GET_CHAT = "GET_CHAT";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAILURE = "GET_CHAT_FAILURE";
